%YAML:1.0
---
image_width: 640
image_height: 480
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: f
   data: [ 2.77191345e+02, 0., 3.20500000e+02, 0., 2.77191345e+02,
       2.40500000e+02, 0., 0., 1. ]
distortion_coefficients: !!opencv-matrix
   rows: 5
   cols: 1
   dt: f
   data: [ 0., 0., 0., 0., 0. ]
