anchor_positions: 
  - [0.650824, 0.516932, 0.45]
  - [0.649123, -0.551066, 0.45]
  - [-0.589174, -0.518907, 0.45]
  - [-0.590875, -0.549091, 0.45]

uwb_topics:
  - '/uwb/tag/iris_bottom_fpv/anchor/anchor0'
  - '/uwb/tag/iris_bottom_fpv/anchor/anchor1'
  - '/uwb/tag/iris_bottom_fpv/anchor/anchor2'
  - '/uwb/tag/iris_bottom_fpv/anchor/anchor3'